
@startuml Diagrama Ejercicio 2.2

enum TipoPlaneta {
    GASEOSO
    TERRESTRE
    ENANO
}

class Planeta {
    + nombre: str
    + cantidad_satelites: int
    + masa: float
    + volumen: float
    + diametro: int
    + distancia_sol: int
    + tipo: TipoPlaneta
    + es_observable: bool
    
    + __init__(nombre: str, cantidad_satelites: int, masa: float, volumen: float, diametro: int, distancia_sol: int, tipo: TipoPlaneta, es_observable: bool)
    + imprimir(): None
    + calcular_densidad(): float
    + es_planeta_exterior(): bool
}

Planeta --> TipoPlaneta 

@enduml